Configuration parameters for log format and prometheus
pgpkeys-eu/hockeypuck pull request #26
Opened 2023-04-17 14:53 UTC by sebix

Add a parameter to define the log format
and an option to disable prometheus

untested, as it turned out my haproxy is too old to use this syntax. Maybe I can use it in the future

2023-04-17 14:56 UTC, mclueppers approved these changes
LGTM

2023-04-17 16:22 UTC, andrewgdotcom requested changes
By default, this will set `log-format` to "", which is probably not what was intended...? :-)

2023-04-17 16:27 UTC, sebix commented
> By default, this will set `log-format` to "", which is probably not what was intended...? :-)

Thanks for catching this. Fixed.

2023-04-17 21:16 UTC, andrewgdotcom commented
Would it be more backwards compatible to define the default log format in docker-compose.yml and keep the line in .env commented out? It doesn't feel very clean...

2023-04-18 17:07 UTC, andrewgdotcom approved these changes
I'll merge this as is, and tidy up in a subsequent commit (I'm expecting a merge conflict anyway...!)

2023-04-18 17:07 UTC, merged